name: spicag
favicon: null
layout_spectrum: 0.6288238496053964
typography_spectrum: 0.5446273896377534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6120771730784327
  lightness: 0.8766077770851552
  saturation: 0.30557235493324697
  rhythmicContrast: 0.43840147741138935
purpose: []
